### ISSUE TITLE
几点修改建议

### ISSUE THREAD

**Issue by filow** [fciasth/web_tasks#1]
1. 在提交代码时，commit信息最好是有意义的内容
2. 要写注释，就算这段代码很简单
3. 考虑使用矩阵乘法来加速运算，see: http://www.cnblogs.com/xudong-bupt/archive/2013/03/19/2966954.html
4. 没有判断输入内容的范围，没有做错误处理，没有向用户提示错误
5. 虽然使用了两种计算方法，但只封装了一个，而且第二个方法还对第一个有部分的依赖（line: 17）
6. 输出的内容中，第一个数字应当是1，不要输出多余的0
7. 虽然使用了数组来保存临时结果，但是却并没有带来任何性能上的提升，反而造成了空间的浪费。如果使用数组可以考虑运行一次后将结果作为缓存，在下一次计算时便可以减少计算量
8. 第一个方法中，由于是递归运算，效率非常低，不推荐使用

检查点评分：
A --- 1. github上存在相应项目目录并且结构正确
B --- 2. fib.rb文件在运行时会首先让用户输入一个1-100之间的数字n，然后他会输出一个1-n的斐波那契数列

额外加分项：
1. 使用了两种方法编写程序

**Comment by filow** [comment]
回归评测意见：
完全没有做任何修改

回归评测评级：C

总评： B

**Comment by fciasth** [comment]
抱歉学长，我这两天帮忙装修家里，昨天你发了B1的新任务我昨晚就把http协议看完了。一直没有修改那个你说的。对不起学长，辜负了你。我先打算把B1任务踏实的完成以后，然后修改那个程序。最近家里事情比较多一直要到23号，请学长谅解～后面我会好好努力的！再次谢谢学长的指导。
13级赵兴海

--- 原始邮件 ---

发件人： "李仁海" <notifications@github.com>
已发： 2015年7月18日 16:56
收件人： "fciasth/web_tasks" <web_tasks@noreply.github.com>
主题： Re: [web_tasks] 几点修改建议 (#1)

回归评测意见：
完全没有做任何修改

回归评测评级：C

总评： B

---
